#R --vanilla --slave <blapred_roc.R
tiff(filename="roc_blapred.tiff",width=4,height=4,units="in",res=600,pointsize=10)
library(ROCR)
#par(mfrow=c(2,2))
aac <- read.table("/Users/abhishikha/Desktop/roc/roc_classic", header=TRUE)
aac_pred <-prediction(aac$pred,aac$val)
aac_perf <- performance(aac_pred, "tpr", "fpr")
aac_perf.auc <- performance(aac_pred, "auc")
aac_perf.auc.area <-slot(aac_perf.auc, "y.values")
curve.area_aac <- mean(unlist(aac_perf.auc.area))
plot(aac_perf, col="black", type="l",lty=1,lwd="1")
mtext(sprintf("%s%1.4f", "classic_PseAAC = ", curve.area_aac), side=3, line=-4, cex=0.7)

aaseq <- read.table("/Users/abhishikha/Desktop/roc/roc_dipep", header=TRUE)
aaseq_pred <-prediction(aaseq$pred,aaseq$val)
aaseq_perf <- performance(aaseq_pred, "tpr", "fpr")
aaseq_perf.auc <- performance(aaseq_pred, "auc")
aaseq_perf.auc.area <-slot(aaseq_perf.auc, "y.values")
curve.area_aaseq <- mean(unlist(aaseq_perf.auc.area))
plot(aaseq_perf, col="green", type="l",lty=1,lwd="1",add=TRUE)
mtext(sprintf("%s%1.4f", "dipeptide = ", curve.area_aaseq), side=3, line=-5, cex=0.7)

#pssm <- read.table("/Users/abhishikha/Desktop/roc/check/pssm", header=TRUE)
#pssm_pred <-prediction(pssm$pred,pssm$val)
#pssm_perf <- performance(pssm_pred, "tpr", "fpr")
#plot(pssm_perf, col="red",lwd="1",type="l",lty=1,add=TRUE)

legend(0.65,0.32,legend=c("classic_PseAAC","dipeptide"),lwd=1,col=c('black','green'),cex=0.7)
dev.off()
q()
